apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  storageClassName: grafana
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
